"""schema initial

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 12:33:33.694843
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('recruitment_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_at'), 'audit_events', ['at'], unique=False)
    op.create_index(op.f('ix_audit_events_company_id'), 'audit_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_events_recruitment_id'), 'audit_events', ['recruitment_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('privacy_contact', sa.String(length=255), nullable=True),
    sa.Column('has_cse', sa.Boolean(), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.Column('retention_months', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_jobs_run_after'), 'jobs', ['run_after'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('purge_schedule',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('due_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('rule', sa.String(length=80), nullable=False),
    sa.Column('done_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity', 'entity_id')
    )
    op.create_index(op.f('ix_purge_schedule_company_id'), 'purge_schedule', ['company_id'], unique=False)
    op.create_index(op.f('ix_purge_schedule_due_at'), 'purge_schedule', ['due_at'], unique=False)
    op.create_index(op.f('ix_purge_schedule_entity_id'), 'purge_schedule', ['entity_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recruitment_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('cost_eur', sa.Float(), nullable=False),
    sa.Column('at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_recruitment_id'), 'usage_records', ['recruitment_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', app.db.EncryptedText(), nullable=True),
    sa.Column('last_name', app.db.EncryptedText(), nullable=True),
    sa.Column('email', app.db.EncryptedText(), nullable=True),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('phone', app.db.EncryptedText(), nullable=True),
    sa.Column('information_delivered_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('pool_consent', sa.Boolean(), nullable=False),
    sa.Column('pool_consent_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_contact_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('access_token_hash', sa.String(length=64), nullable=True),
    sa.Column('access_token_enc', app.db.EncryptedText(), nullable=True),
    sa.Column('anonymized_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_access_token_hash'), 'candidates', ['access_token_hash'], unique=False)
    op.create_index(op.f('ix_candidates_company_id'), 'candidates', ['company_id'], unique=False)
    op.create_index(op.f('ix_candidates_email_hash'), 'candidates', ['email_hash'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('preferred_channel', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_last_inbound_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_table('login_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('proposal_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_tokens_token_hash'), 'login_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_login_tokens_user_id'), 'login_tokens', ['user_id'], unique=False)
    op.create_table('outbound_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('recruitment_id', sa.String(length=36), nullable=True),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('to_address', app.db.EncryptedText(), nullable=False),
    sa.Column('subject', app.db.EncryptedText(), nullable=True),
    sa.Column('body', app.db.EncryptedText(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('sent_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_messages_candidate_id'), 'outbound_messages', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_company_id'), 'outbound_messages', ['company_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_recruitment_id'), 'outbound_messages', ['recruitment_id'], unique=False)
    op.create_table('recruitments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('brief_text', sa.Text(), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('open_questions', sa.JSON(), nullable=False),
    sa.Column('public_token', sa.String(length=40), nullable=False),
    sa.Column('interview_location', sa.String(length=255), nullable=True),
    sa.Column('interview_minutes', sa.Integer(), nullable=False),
    sa.Column('manager_active_seconds', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('hired_application_id', sa.String(length=36), nullable=True),
    sa.Column('retained_3m', sa.Boolean(), nullable=True),
    sa.Column('retained_6m', sa.Boolean(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('profile_validated_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('published_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('shortlist_validated_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('closed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruitments_company_id'), 'recruitments', ['company_id'], unique=False)
    op.create_index(op.f('ix_recruitments_owner_id'), 'recruitments', ['owner_id'], unique=False)
    op.create_index(op.f('ix_recruitments_public_token'), 'recruitments', ['public_token'], unique=True)
    op.create_index(op.f('ix_recruitments_state'), 'recruitments', ['state'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recruitment_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('cv_file_key', sa.String(length=255), nullable=True),
    sa.Column('cv_filename', sa.String(length=255), nullable=True),
    sa.Column('cv_mime', sa.String(length=100), nullable=True),
    sa.Column('cv_text', app.db.EncryptedText(), nullable=True),
    sa.Column('masked_text', app.db.EncryptedText(), nullable=True),
    sa.Column('facts', app.db.EncryptedJSON(), nullable=True),
    sa.Column('message', app.db.EncryptedText(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('group_suggested', sa.String(length=20), nullable=True),
    sa.Column('shortlisted', sa.Boolean(), nullable=False),
    sa.Column('rescued', sa.Boolean(), nullable=False),
    sa.Column('removed_by_manager', sa.Boolean(), nullable=False),
    sa.Column('screened_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruitment_id'], ['recruitments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recruitment_id', 'candidate_id')
    )
    op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_applications_recruitment_id'), 'applications', ['recruitment_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recruitment_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('decided_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('responses_sent_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recruitment_id'], ['recruitments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_recruitment_id'), 'decisions', ['recruitment_id'], unique=False)
    op.create_table('interview_grids',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recruitment_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('removed_questions', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('validated_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recruitment_id'], ['recruitments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_grids_recruitment_id'), 'interview_grids', ['recruitment_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recruitment_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('short_text', sa.Text(), nullable=False),
    sa.Column('long_text', sa.Text(), nullable=False),
    sa.Column('alerts', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('validated_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recruitment_id'], ['recruitments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_recruitment_id'), 'offers', ['recruitment_id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recruitment_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('notified_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('decided_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['recruitment_id'], ['recruitments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_recruitment_id'), 'proposals', ['recruitment_id'], unique=False)
    op.create_index(op.f('ix_proposals_status'), 'proposals', ['status'], unique=False)
    op.create_table('slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recruitment_id', sa.String(length=36), nullable=False),
    sa.Column('start', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('end', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('interview_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['recruitment_id'], ['recruitments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slots_recruitment_id'), 'slots', ['recruitment_id'], unique=False)
    op.create_table('debriefs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('grid_id', sa.String(length=36), nullable=False),
    sa.Column('raw_text', app.db.EncryptedText(), nullable=True),
    sa.Column('notes', app.db.EncryptedJSON(), nullable=True),
    sa.Column('overall', app.db.EncryptedText(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('validated_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debriefs_application_id'), 'debriefs', ['application_id'], unique=True)
    op.create_table('interviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('booking_token_hash', sa.String(length=64), nullable=False),
    sa.Column('booking_token_enc', app.db.EncryptedText(), nullable=True),
    sa.Column('slot_id', sa.String(length=36), nullable=True),
    sa.Column('start', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('end', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('booked_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('invite_reminder_sent_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_application_id'), 'interviews', ['application_id'], unique=False)
    op.create_index(op.f('ix_interviews_booking_token_hash'), 'interviews', ['booking_token_hash'], unique=True)
    op.create_table('screening_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('criterion_id', sa.String(length=20), nullable=False),
    sa.Column('criterion_label', sa.String(length=255), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('justification', app.db.EncryptedText(), nullable=True),
    sa.Column('excerpts', app.db.EncryptedJSON(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('dropped_claims', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_evaluations_application_id'), 'screening_evaluations', ['application_id'], unique=False)
    # Journal d'audit en ajout seul : aucune modification, suppression seulement par la
    # purge de rétention, qui active explicitement wayloop.audit_purge dans sa transaction.
    # Fonction et déclencheur PL/pgSQL : PostgreSQL uniquement (SQLite n'a ni l'un ni l'autre).
    if op.get_bind().dialect.name == "postgresql":
        _audit_append_only()
    # ### end Alembic commands ###


def _audit_append_only() -> None:
    op.execute("""
        CREATE OR REPLACE FUNCTION audit_events_append_only() RETURNS trigger AS $$
        BEGIN
            IF TG_OP = 'DELETE' AND current_setting('wayloop.audit_purge', true) = 'on' THEN
                RETURN OLD;
            END IF;
            RAISE EXCEPTION 'audit_events est en ajout seul (%)', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER audit_events_no_update BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION audit_events_append_only();
    """)


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS audit_events_no_update ON audit_events")
        op.execute("DROP FUNCTION IF EXISTS audit_events_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_evaluations_application_id'), table_name='screening_evaluations')
    op.drop_table('screening_evaluations')
    op.drop_index(op.f('ix_interviews_booking_token_hash'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_application_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_debriefs_application_id'), table_name='debriefs')
    op.drop_table('debriefs')
    op.drop_index(op.f('ix_slots_recruitment_id'), table_name='slots')
    op.drop_table('slots')
    op.drop_index(op.f('ix_proposals_status'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_recruitment_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_offers_recruitment_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_interview_grids_recruitment_id'), table_name='interview_grids')
    op.drop_table('interview_grids')
    op.drop_index(op.f('ix_decisions_recruitment_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_recruitment_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_recruitments_state'), table_name='recruitments')
    op.drop_index(op.f('ix_recruitments_public_token'), table_name='recruitments')
    op.drop_index(op.f('ix_recruitments_owner_id'), table_name='recruitments')
    op.drop_index(op.f('ix_recruitments_company_id'), table_name='recruitments')
    op.drop_table('recruitments')
    op.drop_index(op.f('ix_outbound_messages_recruitment_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_company_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_candidate_id'), table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index(op.f('ix_login_tokens_user_id'), table_name='login_tokens')
    op.drop_index(op.f('ix_login_tokens_token_hash'), table_name='login_tokens')
    op.drop_table('login_tokens')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_candidates_email_hash'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_company_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_access_token_hash'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_usage_records_recruitment_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_purge_schedule_entity_id'), table_name='purge_schedule')
    op.drop_index(op.f('ix_purge_schedule_due_at'), table_name='purge_schedule')
    op.drop_index(op.f('ix_purge_schedule_company_id'), table_name='purge_schedule')
    op.drop_table('purge_schedule')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_run_after'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_audit_events_recruitment_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_company_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
