"""offres et questions

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 13:26:15.701391
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('received_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('applications', sa.Column('answers', app.db.EncryptedJSON(), nullable=True))
    op.add_column('companies', sa.Column('siren', sa.String(length=9), nullable=True))
    op.add_column('companies', sa.Column('naf_code', sa.String(length=10), nullable=True))
    op.add_column('companies', sa.Column('headcount_range', sa.String(length=40), nullable=True))
    op.add_column('companies', sa.Column('plan', sa.String(length=20), nullable=False, server_default='free'))
    op.add_column('companies', sa.Column('plan_status', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('plan_interval', sa.String(length=10), nullable=True))
    op.add_column('companies', sa.Column('plan_period_end', app.db.UTCDateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('stripe_customer_id', sa.String(length=64), nullable=True))
    op.add_column('companies', sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_companies_stripe_customer_id'), 'companies', ['stripe_customer_id'], unique=False)
    op.add_column('screening_evaluations', sa.Column('declared', app.db.EncryptedText(), nullable=True))
    op.add_column('screening_evaluations', sa.Column('evidence', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_evaluations', 'evidence')
    op.drop_column('screening_evaluations', 'declared')
    op.drop_index(op.f('ix_companies_stripe_customer_id'), table_name='companies')
    op.drop_column('companies', 'stripe_subscription_id')
    op.drop_column('companies', 'stripe_customer_id')
    op.drop_column('companies', 'plan_period_end')
    op.drop_column('companies', 'plan_interval')
    op.drop_column('companies', 'plan_status')
    op.drop_column('companies', 'plan')
    op.drop_column('companies', 'headcount_range')
    op.drop_column('companies', 'naf_code')
    op.drop_column('companies', 'siren')
    op.drop_column('applications', 'answers')
    op.drop_table('stripe_events')
    # ### end Alembic commands ###
